webmachinelearning/webnn-baseline

- src/resample2d.js
- test/resample2d_test.js
@fdwr Thanks much for explanations of resample2d by `nearest-neighbor` and `linear` modes on #18 and https://github.com/webmachinelearning/webnn/issues/358, this PR is to sample pixel centers to align with WebNN-Polyfill and Chromium WebNN implementation.
@fdwr @huningxin @lisa0314 PTAL, thanks.
> Implement resample2d

- src/hard_swish.js
- test/hard_swish_test.js
fix #11
@huningxin Please review implementation and tests of **hardSwish** , thanks.
Two new tests of **hardSwish** were referred to [NNAPI CTS tests of **HARD_SWISH**](https://android.googlesource.com/platform/frameworks/ml/+/master/nn/runtime/test/specs/V1_3/hard_swish.mod.py) using their input data. The expected data of **-0.0** having signed flag are different from native ones **0.0**, since JavaScript has signed zeroes  which implements the IEEE Standard for Floating-Point Arithmetic (IEEE 754).
> Implement hardSwish

- src/conv2d.js
- src/conv_transpose2d.js
- src/lib/compute-padding.js
- test/conv_transpose2d_test.js
fix #10
@huningxin @fdwr I use **conv2d** logic to compute **convTranspose2d** with padding input of **convTranspose2d**, PTAL, thanks.
About implementation of **dilation** part, I refer to [PyTorch CONVTRANSPOSE2D](https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html), and verify the implementation by [an ONNX's  convTranspose2d test](https://github.com/onnx/onnx/blob/main/onnx/backend/test/case/node/convtranspose.py#L328).
> Add convTranspose2d implementation.

- src/prelu.js
- test/prelu_test.js
@huningxin @fdwr PTAL, thanks.
> Implement prelu

- src/softplus.js
- test/softplus_test.js
@fdwr @huningxin PTAL, thanks.
> Implement softplus

- src/conv_transpose2d.js
- src/lib/validate-input.js
- test/conv_transpose2d_test.js
@fdwr @huningxin PTAL, thanks.
> Fix implementation issue of convTranspose2d to support options.groups

- src/where.js
- test/where_test.js
@BruceDai @huningxin @fdwr @mingmingtasd PTAL, thanks.
> Implement where

- src/expand.js
- test/expand_test.js
@BruceDai @huningxin @fdwr @fujunwei PTAL, thanks.
> implement expand

- src/layer_normalization.js
- src/lib/validate-input.js
- test/layer_normalization_test.js
@BruceDai @huningxin  @fdwr @shiyi9801 .PTAL, thanks!
> implement  layerNormalization

- src/gather.js
- src/lib/validate-input.js
- test/gather_test.js
@huningxin @fdwr @wacky6 @shiyi9801 PTAL, thanks
> implement gather

- src/arg_max_min.js
- src/lib/validate-input.js
- src/reduce.js
- test/arg_max_min_test.js
- test/reduce_test.js
@huningxin @fdwr @miaobin PTAL, thanks.
> Implement argMax and argMin

- .eslintrc.js
- src/cast.js
- test/cast_test.js
- test/utils.js
@BruceDai @huningxin @fdwr PTAL,thanks!
> Implement cast

- src/lib/validate-input.js
- src/triangular.js
- test/triangular_test.js
@fdwr @huningxin PTAL, thanks.
> Implement triangular

- src/constant.js
- test/constant_test.js
@BruceDai  @fdwr @huningxin @MiaoBin PTAL, thanks!
> Completed constant

- src/lib/validate-input.js
- src/lstm_cell.js
- test/lstm_cell_test.js
@huningxin  @fdwr @shiyi9801 @BruceDai  PTAL, thanks!
> completed lstm_cell

- src/gelu.js
- src/unary.js
- test/gelu_test.js
Fixed #72.
@fdwr @huningxin @mingmingtasd PTAL, thanks.
> Implement gelu

- src/lib/validate-input.js
- src/tile.js
- test/tile_test.js
@huningxin @fdwr PTAL, thanks.
> Implement tile

- src/quantize_linear.js
- test/quantize_linear_test.js
@huningxin @fdwr @lisa0314 PTAL, thanks.
> Implement quantizeLinear

- src/dequantize_linear.js
- test/dequantize_linear_test.js
@huningxin @fdwr @lisa0314 PTAL, thanks.
> Implement dequantizeLinear

- src/gather.js
- src/lib/validate-input.js
- test/gather_test.js
@huningxin @fdwr PTAL, thanks.
> Support negative indices of gather op

- src/lib/validate-input.js
- src/scatter_elements.js
- src/unary.js
- test/scatter_elements_test.js
- test/unary_test.js
@huningxin @fdwr @shiyi9801 PTAL, thanks.
> Implement scatterElements

- src/logical.js
- test/logical_test.js
Fixed #108.
@fdwr @huningxin PTAL, thanks.
> Add more logical ops

- src/lib/validate-input.js
- src/slice.js
- test/slice_test.js
This PR is to fix #112.
@fdwr @huningxin @shiyi9801 PTAL, thanks!
> support strides options for slice op

- src/lib/validate-input.js
- src/reduce.js
- src/reverse.js
- test/reverse_test.js
This PR is to fixe #110.
@fdwr @huningxin @shiyi9801 PTAL, thanks!
> implement reverse

- src/lib/validate-input.js
- test/scatter_elements_test.js
- test/utils.js
This PR is to fix #121.
@fdwr @huningxin PTAL, thanks!
> check overlapping indices of scatterElements

- src/gather_nd.js
- src/lib/validate-input.js
- test/gather_nd_test.js
This PR is to fix #87.
@fdwr @huningxin @shiyi9801 PTAL, thanks!
> implement gatherND

- src/lib/validate-input.js
- src/scatter_nd.js
- test/scatter_nd_test.js
This PR is to fix #86.
@fdwr @huningxin PTAL, thanks!
> implement scatterND

- src/lstm.js
- test/lstm_test.js
@fdwr @huningxin PTAL, thanks!
> Fix output sequence issue of lstm with backward direction and both direction

- src/pool2d.js
- src/reduce.js
- test/l2pool2d_test.js
This PR is to fix the issue reported on https://issues.chromium.org/issues/383232123, the details of issue-383232123 as below.
```
Two tests cases fail on multiple platforms due to incorrect expected results when the output size is rounded up, requiring implicit zero padding:
l2Pool2d float32 4D tensor options.roundingType=ceil
l2Pool2d float32 4D tensor options.outputSizes ignores options.roundingType=floor
Both give following error for the [0, 2] output element:
assert_true: assert_array_approx_equals_ulp: test l2Pool2d float32 actual 90.6768569946289 should be
close enough to expected 8222.29296875 by the acceptable 11 ULP distance, but they have 55254687 ULP
distance expected true got false
The expected value of 8222 is not possible since the input elements are all < 100. The actual …
```
> Fixed wrong result for l2Pool2d when sliding window having two valid elements
